### ISSUE TITLE
Compile - Fails

### ISSUE THREAD

**Issue by vignesh02** [spiderkeys/BebopRebopAPI#1]
Just now pulled your code and ran the make command but getting below error. Can you please share your thought on this?

ubuntu@ubuntu:~/BebopRebopAPI/Build$ pwd
/home/ubuntu/BebopRebopAPI/Build
ubuntu@ubuntu:~/BebopRebopAPI/Build$ make
Building file: ../Source/CBebopInterface.cpp
Invoking: GCC C++ Compiler
g++ -I../ThirdPartyLibs/ArDroneSDK3/include -I../ThirdPartyLibs/rapidjson/include -I../ThirdPartyLibs/easyloggingpp/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"CBebopInterface.d" -MT"CBebopInterface.d" -o "CBebopInterface.o" "../Source/CBebopInterface.cpp"
/bin/sh: 1: g++: not found
make: *** [CBebopInterface.o] Error 127
ubuntu@ubuntu:~/BebopRebopAPI/Build$ 

I really appreciate your help.

**Comment by vignesh02** [comment]
Hi Charles,
I have noticed g++ was not installed and installed now. Ran the make command under the Build folder got the below message. Do not know next step to run the program and navigate the Drone from your code. Can you please share the detail information.

ubuntu@ubuntu:~/BebopRebopAPI/Source$ sudo apt-get install g++
Reading package lists... Done
Building dependency tree      
Reading state information... Done
The following extra packages will be installed:
  g++-4.8 libstdc++-4.8-dev
Suggested packages:
  g++-multilib g++-4.8-multilib gcc-4.8-doc libstdc++6-4.8-dbg
  libstdc++-4.8-doc
The following NEW packages will be installed:
  g++ g++-4.8 libstdc++-4.8-dev
0 upgraded, 3 newly installed, 0 to remove and 310 not upgraded.
Need to get 8,090 kB of archives.
After this operation, 29.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libstdc++-4.8-dev amd64 4.8.2-19ubuntu1 [1,050 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main g++-4.8 amd64 4.8.2-19ubuntu1 [7,038 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main g++ amd64 4:4.8.2-1ubuntu6 [1,490 B]
Fetched 8,090 kB in 38s (213 kB/s)                                            
Selecting previously unselected package libstdc++-4.8-dev:amd64.
(Reading database ... 170667 files and directories currently installed.)
Preparing to unpack .../libstdc++-4.8-dev_4.8.2-19ubuntu1_amd64.deb ...
Unpacking libstdc++-4.8-dev:amd64 (4.8.2-19ubuntu1) ...
Selecting previously unselected package g++-4.8.
Preparing to unpack .../g++-4.8_4.8.2-19ubuntu1_amd64.deb ...
Unpacking g++-4.8 (4.8.2-19ubuntu1) ...
Selecting previously unselected package g++.
Preparing to unpack .../g++_4%3a4.8.2-1ubuntu6_amd64.deb ...
Unpacking g++ (4:4.8.2-1ubuntu6) ...
Processing triggers for man-db (2.6.7.1-1) ...
Setting up libstdc++-4.8-dev:amd64 (4.8.2-19ubuntu1) ...
Setting up g++-4.8 (4.8.2-19ubuntu1) ...
Setting up g++ (4:4.8.2-1ubuntu6) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
ubuntu@ubuntu:~/BebopRebopAPI/Source$ cd ..
ubuntu@ubuntu:~/BebopRebopAPI$ cd Build/
ubuntu@ubuntu:~/BebopRebopAPI/Build$ make
Building file: ../Source/CBebopInterface.cpp
Invoking: GCC C++ Compiler
g++ -I../ThirdPartyLibs/ArDroneSDK3/include -I../ThirdPartyLibs/rapidjson/include -I../ThirdPartyLibs/easyloggingpp/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"CBebopInterface.d" -MT"CBebopInterface.d" -o "CBebopInterface.o" "../Source/CBebopInterface.cpp"
Finished building: ../Source/CBebopInterface.cpp
 
Building file: ../Source/CCommandPacket.cpp
Invoking: GCC C++ Compiler
g++ -I../ThirdPartyLibs/ArDroneSDK3/include -I../ThirdPartyLibs/rapidjson/include -I../ThirdPartyLibs/easyloggingpp/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"CCommandPacket.d" -MT"CCommandPacket.d" -o "CCommandPacket.o" "../Source/CCommandPacket.cpp"
Finished building: ../Source/CCommandPacket.cpp
 
Building file: ../Source/CNetworkInterface.cpp
Invoking: GCC C++ Compiler
g++ -I../ThirdPartyLibs/ArDroneSDK3/include -I../ThirdPartyLibs/rapidjson/include -I../ThirdPartyLibs/easyloggingpp/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"CNetworkInterface.d" -MT"CNetworkInterface.d" -o "CNetworkInterface.o" "../Source/CNetworkInterface.cpp"
Finished building: ../Source/CNetworkInterface.cpp
 
Building file: ../Source/CNetworkSettings.cpp
Invoking: GCC C++ Compiler
g++ -I../ThirdPartyLibs/ArDroneSDK3/include -I../ThirdPartyLibs/rapidjson/include -I../ThirdPartyLibs/easyloggingpp/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"CNetworkSettings.d" -MT"CNetworkSettings.d" -o "CNetworkSettings.o" "../Source/CNetworkSettings.cpp"
Finished building: ../Source/CNetworkSettings.cpp
 
Building file: ../Source/CVehicleInterface.cpp
Invoking: GCC C++ Compiler
g++ -I../ThirdPartyLibs/ArDroneSDK3/include -I../ThirdPartyLibs/rapidjson/include -I../ThirdPartyLibs/easyloggingpp/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"CVehicleInterface.d" -MT"CVehicleInterface.d" -o "CVehicleInterface.o" "../Source/CVehicleInterface.cpp"
Finished building: ../Source/CVehicleInterface.cpp
 
Building target: libBebopRebopAPI.a
Invoking: GCC Archiver
ar -r  "libBebopRebopAPI.a"  ./CBebopInterface.o ./CCommandPacket.o ./CNetworkInterface.o ./CNetworkSettings.o ./CVehicleInterface.o
ar: creating libBebopRebopAPI.a
Finished building target: libBebopRebopAPI.a
Running post-build script to move files into their proper locations
../Scripts/postbuild.sh
rm: cannot remove ‘./Build/*.d’: No such file or directory
rm: cannot remove ‘./Build/*.o’: No such file or directory
make: [libBebopRebopAPI.a] Error 1 (ignored)
ubuntu@ubuntu:~/BebopRebopAPI/Build$

**Comment by vignesh02** [comment]
Hi Charles,

Let me explain the step by step aken from me to run your code.

1. git clone https://github.com/spiderkeys/BebopRebopAPI.git
2. cd /home/ubuntu/BebopRebopAPI/Build
3. ran the make command and below was the output
Building target: libBebopRebopAPI.a
Invoking: GCC Archiver
ar -r  "libBebopRebopAPI.a"  ./CBebopInterface.o ./CCommandPacket.o ./CNetworkInterface.o ./CNetworkSettings.o ./CVehicleInterface.o 
ar: creating libBebopRebopAPI.a
Finished building target: libBebopRebopAPI.a
Running post-build script to move files into their proper locations
../Scripts/postbuild.sh
rm: cannot remove ‘./Build/*.d’: No such file or directory
rm: cannot remove ‘./Build/*.o’: No such file or directory
make: [libBebopRebopAPI.a] Error 1 (ignored)

4. Moved to cd /home/ubuntu/BebopRebopAPI/Samples/SimpleBebop and ran the main.cpp using below command
gcc main.cpp -o main.out

Output
main.cpp:2:29: fatal error: CBebopInterface.h: No such file or directory
 #include "CBebopInterface.h"
                             ^
compilation terminated.

5. copied the main.cpp to source folder cp main.cpp /home/ubuntu/BebopRebopAPI/Source
6. Ran the main.cpp in the Source folder by giving below command
gcc main.cpp -o main.out

Output
In file included from CVehicleInterface.h:4:0,
                 from CBebopInterface.h:4,
                 from main.cpp:2:
CNetworkInterface.h:12:28: fatal error: libARSAL/ARSAL.h: No such file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.

Can you please tell me how to resolve this and make my drone to take off..

I really appreciate your help.

**Comment by vignesh02** [comment]
Hi Charles,

Let me explain the step by step aken from me to run your code.

1. git clone https://github.com/spiderkeys/BebopRebopAPI.git
2. cd /home/ubuntu/BebopRebopAPI/Build
3. ran the make command and below was the output
Building target: libBebopRebopAPI.a
Invoking: GCC Archiver
ar -r  "libBebopRebopAPI.a"  ./CBebopInterface.o ./CCommandPacket.o ./CNetworkInterface.o ./CNetworkSettings.o ./CVehicleInterface.o 
ar: creating libBebopRebopAPI.a
Finished building target: libBebopRebopAPI.a
Running post-build script to move files into their proper locations
../Scripts/postbuild.sh
rm: cannot remove ‘./Build/*.d’: No such file or directory
rm: cannot remove ‘./Build/*.o’: No such file or directory
make: [libBebopRebopAPI.a] Error 1 (ignored)

4. Moved to cd /home/ubuntu/BebopRebopAPI/Samples/SimpleBebop and ran the main.cpp using below command
gcc main.cpp -o main.out

Output
main.cpp:2:29: fatal error: CBebopInterface.h: No such file or directory
 #include "CBebopInterface.h"
                             ^
compilation terminated.

5. copied the main.cpp to source folder cp main.cpp /home/ubuntu/BebopRebopAPI/Source
6. Ran the main.cpp in the Source folder by giving below command
gcc main.cpp -o main.out

Output
In file included from CVehicleInterface.h:4:0,
                 from CBebopInterface.h:4,
                 from main.cpp:2:
CNetworkInterface.h:12:28: fatal error: libARSAL/ARSAL.h: No such file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.

Can you please tell me how to resolve this and make my drone to take off..

I really appreciate your help.

**Comment by spiderkeys** [comment]
Hi Vignesh,

I've decided to change this project back to an executable, and think it is best served as a source-only wrapper, rather than library. This simplifies the usage.

I've fixed some of the problems that you've been seeing and it should be fairly simple to test this out now. Do the following:

1. Clone the latest version of the repo
2. Build the project (cd to /Build/ and run make)
3. Run the executable
4. Enter any key to make it take off.
5. Enter any key to make it land.

One thing to note, you're going to get spammed with a lot of "buffer full" messages, since the code is not currently pulling data out of the buffers that the drone is sending data to (nav data, acknowledgments, etc). This won't hurt anything but it is annoying. This will go away once I implement a reader thread which pulls data out of that buffer and sends it to the user's codespace.

If takeoff and landing work, the other commands should as well. I got a better flight yesterday using this exact code. Unfortunately, the Bebop has an extremely low payload (struggles to carry 150g!), whereas the ArDrone 2 can carry something like 600g. It had a lot of trouble carrying the Raspberry pi and the small battery for the Pi.

**Comment by vignesh02** [comment]
Hi Charles,

Thank you very much for your awesome code. It all worked out exactly as you said. Now, what is the procedure for controlling Bepop drone and navigating using pilot commands and also capturing the image. Thanks in Anticipation.

**Comment by vignesh02** [comment]
Hi Charles,

Can you please give us some code for capturing a pic through the camera. There are 4 parameters that needs to be passed, we would like some sample code for the 4th parameter - storage ID. Otherwise, if you have some code for image capture, please share that with us. Thanks in Anticipation.

**Comment by spiderkeys** [comment]
Hi Vignesh,

Sorry, but I haven't worked on this for the past few days. I still have not added any support for video or parsing received commands, only pilot commands. After doing some payload testing with the bebop, we found that it was having a lot of trouble carrying our single board computers, and that the AR Drone 2 was capable of lifting quite a lot more. That kind of pushed the Bebop off of my radar for a bit while I go back to working with the AR Drone 2 for some upcoming demos. One thing I might do is explore the possibility of taking the electronics off of the bebop and moving them over to the AR Drone 2. I think if Parrot did this, they would find that it would be their best drone yet.

In the meantime, if you want to take a shot at getting video working yourself, I would suggest that you look at this Sample project on the Parrot repo:

https://github.com/ARDroneSDK3/Samples/tree/master/Unix/BebopDroneReceiveStream

This will get you basic video streaming (but I'm not sure if it will actually display it for you). Maybe you or someone else could wrap that example up within my framework to help flesh things out?

**Comment by vignesh02** [comment]
Hi Charles,

Thanks for your response.

I was totally blocked because of mass storage id.

eARCOMMANDS_GENERATOR_ERROR ARCOMMANDS_Generator_GenerateARDrone3MediaRecordPicture  ( uint8_t *  buffer,  
  int32_t  buffLen,  
  int32_t *  cmdLen,  
  uint8_t  _mass_storage_id  
 )

eARCOMMANDS_GENERATOR_ERROR ARCOMMANDS_Generator_GenerateARDrone3MediaRecordStatePictureStateChanged  ( uint8_t *  buffer,  
  int32_t  buffLen,  
  int32_t *  cmdLen,  
  uint8_t  _state,  
  uint8_t  _mass_storage_id  
 ) 


If you come across the value for mass storage id please update me.

**Comment by vignesh02** [comment]
Hi Charles,

I have taken your code and modified few changes now and shall I share the code or upload it here

1. Instead of pressing any key for takeoff and landoff used getch to capture user keyword and do pilot command.
2. Added take picture interface to capture image. Mass storage id is zero.

Thanks for your support.

**Comment by spiderkeys** [comment]
That's great! The best way to handle sharing the code so I can merge it in is to fork the repository, add in your changes, and then make a pull request. I will then merge your additions in.

**Comment by vignesh02** [comment]
Hi Charles,

I have attached the file that we made changes to existing code. Please
review and update to the repository.

Thanks & Regards,
Vigneshwaran Ganesan

**Comment by murariuroger** [comment]
Hi Charles,

I tryed what you suggested, but I get the following : [make: Nothing to be done for `Source/CBebopInterface.d' ]

**Comment by murariuroger** [comment]
Hi Charles,

I tried what you suggested:
    Clone the latest version of the repo
    Build the project (cd to /Build/ and run make) <---- I get the following here:  [make: Nothing to be done for `Source/CBebopInterface.d' ]
   
Do you have any idea why?

**Comment by murariuroger** [comment]
Nevermind, I tried from eclipse and worked. Thx

**Comment by dk683** [comment]
Dear @vignesh02, 

Hello. I could not find the code that enables BeBop to be controlled by user keyword and capture image. 
If you don't mind, could you tell me where I could find the code?
I appreciate your help!

Sincerely,

Dong Ki Kim
